package com.futureproducts.gbrself.models

data class Data(
    val actual_price: String,
    val address: String,
    val brand: String,
    val brand_id: String,
    val country_id: String,
    val country_name: String,
    val dis_id: String,
    val dis_name: String,
    val discount_price: String,
    val dse_id: Int,
    val dse_name: String,
    val format: String,
    val governate_id: String,
    val governate_name: String,
    val item_total: Int,
    val locality_id: String,
    val locality_name: String,
    val model: String,
    val model_name: String,
    val order_no: Int,
    val order_total: String,
    val product_id: String,
    val product_name: String,
    val qty: String,
    val ret_id: Int,
    val ret_mobile: String,
    val ret_name: String,
    val serialized: String,
    val sku: String,
    val time: String,
    val ttl_qty: String,
    val payment_mode: String,
    val payment_type: String,
    val  payment_description: String
)